### ISSUE TITLE
cant work

### ISSUE THREAD

**Issue by harryudaya** [r1cebank/Awtrix-ESP32#1]
I have changed the code to suite my arduino in PC to run the code to ESP32 ,and my awtrix can display WIFI when give a 5V voltage, so how to do next? no infor then

**Comment by r1cebank** [comment]
Sorry, this was a pet project I did trying to port ESP32 over, i never finished so it won't work now.

**Comment by harryudaya** [comment]
any other things need to do? How to  do next? and when can u finished that? hope ur feedback, thanks!
